version: '2'
services:
  ansibledocker:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50001:50000"
      - "8081:8080"
    container_name : ansiblejenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /root/jenkins/files/ssh.conf:/root/.ssh/ 
      - /root/jenkins/files/.aws:/root/.aws/
      - /root/jenkins/files/ansible-ssh/ansible:/etc/ansible/
      - /root/jenkins/files/ansible-ssh/ansibledir/:/ansible/playbooks          
